[package]
name = "password-strength-checker"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/sts10/password-strength-checker"
authors = ["sts10 <sschlinkert@gmail.com>"]
license = "BlueOak-1.0.0"

[dependencies]
zxcvbn = "2.2.2"
rpassword = "7.2.0"
